name: gwas-analysis-default
channels:
  - conda-forge
  - defaults
dependencies:
  - dask=2.14.0
  - distributed=2.15.0
  - jupyterlab=2.1.1
  - matplotlib=3.1.3
  - numba=0.49.0
  - numcodecs=0.6.4
  - numpy=1.18.1
  - pillow=7.0.0
  - pip=20.0.2
  - plotly=4.6.0
  - python=3.7.7
  - python-dotenv=0.13.0
  - pip:
    - hail==0.2.38
